# Generated by Django 2.0.6 on 2018-10-20 15:36

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpensesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField()),
                ('emergency_fund', models.IntegerField()),
                ('emergency_fund_status', models.CharField(max_length=200)),
                ('date_of_balance', models.DateField(default=datetime.datetime(2018, 10, 20, 15, 36, 47, 696017))),
                ('date_of_emergency', models.DateField(default=datetime.datetime(2018, 10, 20, 15, 36, 47, 696043))),
                ('username', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
