# Generated by Django 2.0.6 on 2018-10-20 15:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('expenseApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensesmodel',
            name='date_of_balance',
            field=models.DateField(default=datetime.datetime(2018, 10, 20, 15, 38, 11, 589238, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='expensesmodel',
            name='date_of_emergency',
            field=models.DateField(default=datetime.datetime(2018, 10, 20, 15, 38, 11, 589262, tzinfo=utc)),
        ),
    ]
