# Generated by Django 2.0.6 on 2018-10-20 15:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('expenseApp', '0002_auto_20181020_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensesmodel',
            name='date_of_balance',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='expensesmodel',
            name='date_of_emergency',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
