# Generated by Django 2.0.6 on 2018-10-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenseApp', '0003_auto_20181020_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensesmodel',
            name='account_name',
            field=models.CharField(blank=True, default=True, max_length=200, null=True),
        ),
    ]
