# Generated by Django 2.0.6 on 2018-10-22 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenseApp', '0006_usersetup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersetup',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
