# Generated by Django 2.0.6 on 2018-10-22 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenseApp', '0007_auto_20181022_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensesmodel',
            name='deposit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expensesmodel',
            name='expense',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
