# Generated by Django 2.0.6 on 2018-10-23 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expenseApp', '0011_auto_20181022_1942'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('time_of_transaction', models.DateField()),
            ],
        ),
        migrations.RenameModel(
            old_name='ExpensesModel',
            new_name='AccountModel',
        ),
        migrations.AddField(
            model_name='transactionmodel',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenseApp.AccountModel'),
        ),
    ]
