# Generated by Django 2.0.6 on 2018-10-23 22:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('expenseApp', '0012_auto_20181023_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionmodel',
            name='which_account',
            field=models.CharField(blank=True, default='Main Account', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='transactionmodel',
            name='time_of_transaction',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
