# Generated by Django 2.0.6 on 2018-10-24 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenseApp', '0013_auto_20181023_2211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountmodel',
            old_name='expense',
            new_name='checking',
        ),
        migrations.RemoveField(
            model_name='accountmodel',
            name='date_of_emergency',
        ),
        migrations.RemoveField(
            model_name='accountmodel',
            name='emergency_fund',
        ),
        migrations.RemoveField(
            model_name='accountmodel',
            name='emergency_fund_status',
        ),
        migrations.AddField(
            model_name='accountmodel',
            name='savings',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='accountmodel',
            name='balance',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
