# Generated by Django 2.0.6 on 2018-10-24 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenseApp', '0014_auto_20181024_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountmodel',
            name='expense',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
