# Generated by Django 2.0.6 on 2018-10-26 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenseApp', '0015_accountmodel_expense'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactionmodel',
            old_name='which_account',
            new_name='transaction',
        ),
        migrations.AlterField(
            model_name='accountmodel',
            name='account_name',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
